version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: edu_postgres_db
    environment:
      - POSTGRES_DB=edu_analytics
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=super_senha_segura
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # A Fila do Ecossistema
  redis:
    image: redis:7-alpine
    container_name: edu_redis_broker
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: django_api_container
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-chave-de-teste-ecossistema-integrado-2026
    depends_on:
      - db
      - redis

  # O Trabalhador em Segundo Plano (Background Worker)
  worker:
    build: .
    container_name: celery_worker_container
    command: celery -A escola worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-chave-de-teste-ecossistema-integrado-2026
    depends_on:
      - db
      - redis

volumes:
  postgres_data: