# Generated by Django 6.0.6 on 2026-07-05 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='email',
        ),
        migrations.AddField(
            model_name='aluno',
            name='situacao',
            field=models.CharField(default='Ativo', max_length=50),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='BoletimBimestral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimestre', models.IntegerField(choices=[(1, '1º Bimestre'), (2, '2º Bimestre')])),
                ('nota', models.FloatField(blank=True, null=True)),
                ('faltas', models.IntegerField(default=0)),
                ('aulas_computadas', models.IntegerField(default=0)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletins', to='escola.aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.disciplina')),
            ],
            options={
                'unique_together': {('aluno', 'disciplina', 'bimestre')},
            },
        ),
        migrations.DeleteModel(
            name='MetricaDesempenho',
        ),
    ]
