# Generated by Django 6.0.6 on 2026-07-05 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "escola",
            "0002_disciplina_remove_aluno_criado_em_remove_aluno_email_and_more",
        ),
    ]

    operations = [
        # 1. Criação da VIEW Analítica de Médias da Turma (Compatível com PostgreSQL)
        migrations.RunSQL(
            sql="""
            CREATE VIEW view_diagnostico_turma AS
            SELECT 
                MIN(b.id) AS id,
                d.nome AS disciplina,
                AVG(CASE WHEN b.bimestre = 1 THEN b.nota END) AS media_turma_1b,
                AVG(CASE WHEN b.bimestre = 2 THEN b.nota END) AS media_turma_2b,
                SUM(b.faltas) AS total_faltas_acumuladas
            FROM escola_boletimbimestral b
            JOIN escola_disciplina d ON b.disciplina_id = d.id
            GROUP BY d.nome;
            """,
            reverse_sql="DROP VIEW IF EXISTS view_diagnostico_turma;",
        ),
        # 2. Criação do TRIGGER de Alerta de Frequência por Componente (Compatível com PostgreSQL)
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION alertar_faltas_func()
            RETURNS TRIGGER AS $$
            BEGIN
                IF NEW.faltas > 10 THEN
                    UPDATE escola_aluno 
                    SET situacao = 'Alerta de Frequência' 
                    WHERE id = NEW.aluno_id;
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            CREATE OR REPLACE TRIGGER sistema_alerta_faltas
            AFTER UPDATE ON escola_boletimbimestral
            FOR EACH ROW
            EXECUTE FUNCTION alertar_faltas_func();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS sistema_alerta_faltas ON escola_boletimbimestral;
            DROP FUNCTION IF EXISTS alertar_faltas_func();
            """,
        ),
    ]
