# Generated by Django 6.0.6 on 2026-07-06 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_criar_estrutura_analitica'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticoTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=255)),
                ('media_turma_1b', models.FloatField()),
                ('media_turma_2b', models.FloatField()),
                ('total_faltas_acumuladas', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Diagnóstico da Turma',
                'verbose_name_plural': 'Diagnósticos da Turma',
                'db_table': 'view_diagnostico_turma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IntervencaoPedagogica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_acao', models.TextField(verbose_name='Descrição da Intervenção (Ex: Recuperação Paralela, Mudança de Assento)')),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Planejada / Pendente'), ('EM_ANDAMENTO', 'Em Execução'), ('CONCLUIDA', 'Concluída com Sucesso'), ('INEFICAZ', 'Executada sem Evolução')], default='PENDENTE', max_length=20)),
                ('observacoes_retorno', models.TextField(blank=True, null=True, verbose_name='Feedback / Evolução do Estudante')),
            ],
            options={
                'verbose_name': 'Intervenção Pedagógica',
                'verbose_name_plural': 'Intervenções Pedagógicas',
            },
        ),
        migrations.CreateModel(
            name='SarespResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente_tecnico', models.CharField(max_length=150, unique=True, verbose_name='Componente Técnico')),
                ('media_estado', models.FloatField(verbose_name='Média do Estado')),
                ('percentual_proficiencia_avancado', models.FloatField(default=0.0, verbose_name=' % Avançado (Estado)')),
            ],
            options={
                'verbose_name': 'Resultado SARESP',
                'verbose_name_plural': 'Resultados SARESP',
            },
        ),
        migrations.AlterModelOptions(
            name='boletimbimestral',
            options={'verbose_name': 'Boletim Bimestral', 'verbose_name_plural': 'Boletins Bimestrais'},
        ),
        migrations.AlterUniqueTogether(
            name='boletimbimestral',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Matrícula (SED)'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome do Aluno'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='situacao',
            field=models.CharField(default='Ativo', max_length=50, verbose_name='Situação Acadêmica'),
        ),
        migrations.AlterField(
            model_name='boletimbimestral',
            name='aulas_computadas',
            field=models.IntegerField(default=0, verbose_name='Aulas Dadas'),
        ),
        migrations.AlterField(
            model_name='boletimbimestral',
            name='bimestre',
            field=models.IntegerField(choices=[(1, '1º Bimestre'), (2, '2º Bimestre')], verbose_name='Bimestre'),
        ),
        migrations.AlterField(
            model_name='boletimbimestral',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletins', to='escola.disciplina'),
        ),
        migrations.AlterField(
            model_name='boletimbimestral',
            name='faltas',
            field=models.IntegerField(default=0, verbose_name='Quantidade de Faltas'),
        ),
        migrations.AlterField(
            model_name='boletimbimestral',
            name='nota',
            field=models.FloatField(blank=True, null=True, verbose_name='Nota Real'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código da Disciplina'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome do Componente Curricular'),
        ),
        migrations.AddConstraint(
            model_name='boletimbimestral',
            constraint=models.UniqueConstraint(fields=('aluno', 'disciplina', 'bimestre'), name='unique_boletim_aluno_disciplina_bimestre'),
        ),
        migrations.AddField(
            model_name='intervencaopedagogica',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervencoes', to='escola.aluno'),
        ),
        migrations.AddField(
            model_name='intervencaopedagogica',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervencoes', to='escola.disciplina'),
        ),
    ]
