# Generated by Django 6.0.6 on 2026-07-06 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_diagnosticoturma_intervencaopedagogica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricaDesempenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nota Consolidada')),
                ('frequencia_porcentagem', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Frequência (%)')),
                ('data_avaliacao', models.DateField(blank=True, null=True, verbose_name='Data da Avaliação')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas_desempenho', to='escola.aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas_desempenho', to='escola.disciplina')),
            ],
            options={
                'verbose_name': 'Métrica de Desempenho',
                'verbose_name_plural': 'Métricas de Desempenho',
            },
        ),
    ]
