# Generated by Django 6.0.6 on 2026-07-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0005_metricadesempenho'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='boletimbimestral',
            index=models.Index(fields=['aluno', 'disciplina', 'bimestre'], name='escola_bole_aluno_i_59fccd_idx'),
        ),
        migrations.AddIndex(
            model_name='boletimbimestral',
            index=models.Index(fields=['disciplina', 'bimestre'], name='escola_bole_discipl_4fb0ec_idx'),
        ),
        migrations.AddIndex(
            model_name='intervencaopedagogica',
            index=models.Index(fields=['status'], name='escola_inte_status_0d8058_idx'),
        ),
        migrations.AddIndex(
            model_name='metricadesempenho',
            index=models.Index(fields=['disciplina'], name='escola_metr_discipl_b914b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='metricadesempenho',
            constraint=models.UniqueConstraint(fields=('aluno', 'disciplina'), name='unique_metricas_aluno_disciplina'),
        ),
    ]
