# Generated by Django 6.0.6 on 2026-07-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0006_boletimbimestral_escola_bole_aluno_i_59fccd_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='boletimbimestral',
            name='escola_bole_discipl_4fb0ec_idx',
        ),
        migrations.RemoveIndex(
            model_name='metricadesempenho',
            name='escola_metr_discipl_b914b3_idx',
        ),
        migrations.AddIndex(
            model_name='boletimbimestral',
            index=models.Index(fields=['disciplina', 'bimestre', 'nota'], name='idx_boletim_window_perf'),
        ),
        migrations.AddIndex(
            model_name='metricadesempenho',
            index=models.Index(fields=['disciplina_id'], name='escola_metr_discipl_b914b3_idx'),
        ),
    ]
